"""add denormalized resume fields and merge template fields, seed starter templates

Revision ID: f5ee209957e2
Revises: 643628e65fca
Create Date: 2026-07-09 04:50:43.259909

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ee209957e2'
down_revision: Union[str, None] = '643628e65fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed ids so the downgrade can remove exactly these seeded rows (and
# nothing a user may have since renamed) rather than matching by name.
_MODERN_ID = str(uuid.uuid4())
_PROFESSIONAL_ID = str(uuid.uuid4())
_MINIMAL_ID = str(uuid.uuid4())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_resumes_email'), 'resumes', ['email'], unique=False)
    op.create_index(op.f('ix_resumes_full_name'), 'resumes', ['full_name'], unique=False)
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('html_template_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    # ---- Seed the 3 starter templates ----
    templates_table = sa.table(
        'templates',
        sa.column('id', postgresql.UUID(as_uuid=False)),
        sa.column('name', sa.String),
        sa.column('category', sa.String),
        sa.column('description', sa.Text),
        sa.column('preview_image', sa.String),
        sa.column('html_template_path', sa.String),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(
        templates_table,
        [
            {
                'id': _MODERN_ID,
                'name': 'Modern',
                'category': 'modern',
                'description': 'A clean, contemporary layout with a bold header and clear section dividers.',
                'preview_image': '/static/templates/modern/preview.png',
                'html_template_path': 'templates/modern.html',
                'is_active': True,
            },
            {
                'id': _PROFESSIONAL_ID,
                'name': 'Professional',
                'category': 'professional',
                'description': 'A traditional, ATS-friendly layout suited for corporate and formal applications.',
                'preview_image': '/static/templates/professional/preview.png',
                'html_template_path': 'templates/professional.html',
                'is_active': True,
            },
            {
                'id': _MINIMAL_ID,
                'name': 'Minimal',
                'category': 'minimal',
                'description': 'A stripped-back, whitespace-forward layout that keeps the focus on content.',
                'preview_image': '/static/templates/minimal/preview.png',
                'html_template_path': 'templates/minimal.html',
                'is_active': True,
            },
        ],
    )


def downgrade() -> None:
    # ---- Remove the seeded starter templates ----
    op.execute(
        sa.text("DELETE FROM templates WHERE id IN (:modern, :professional, :minimal)").bindparams(
            modern=_MODERN_ID, professional=_PROFESSIONAL_ID, minimal=_MINIMAL_ID
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'html_template_path')
    op.drop_column('templates', 'description')
    op.drop_index(op.f('ix_resumes_full_name'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_email'), table_name='resumes')
    op.drop_column('resumes', 'certifications')
    op.drop_column('resumes', 'projects')
    op.drop_column('resumes', 'experience')
    op.drop_column('resumes', 'education')
    op.drop_column('resumes', 'skills')
    op.drop_column('resumes', 'summary')
    op.drop_column('resumes', 'portfolio_url')
    op.drop_column('resumes', 'github_url')
    op.drop_column('resumes', 'linkedin_url')
    op.drop_column('resumes', 'location')
    op.drop_column('resumes', 'phone')
    op.drop_column('resumes', 'email')
    op.drop_column('resumes', 'full_name')
    # ### end Alembic commands ###
